name: Build and Deploy with Bun

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    container:
      image: oven/bun  # Specify the Bun Docker image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install git
        run: |
          apt-get update
          apt-get install -y git

      - name: Install Dependencies
        run: bun install

      - name: Build Application
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.APRIL_TOKEN }}
          publish_dir: ./dist # Replace with the directory containing index.html and assets

      
